export const agentLayout = [
  {
    i: "TeamOne",
    x: 1,
    y: 1,
    w: 1,
    h: 6.2,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "TeamTwo",
    x: 0,
    y: 1,
    w: 1,
    h: 6.2,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "TeamThree",
    x: 1,
    y: 1,
    w: 1,
    h: 6.2,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "TeamFour",
    x: 0,
    y: 6,
    w: 1,
    h: 6.2,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "TeamFive",
    x: 1,
    y: 1,
    w: 1,
    h: 6.2,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "TeamSix",
    x: 0,
    y: 1,
    w: 1,
    h: 6.2,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
];
