export const overviewLayout = [
  {
    i: "ScoreCardTable",
    x: 1,
    y: 8,
    w: 1,
    h: 32,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "AverageScore",
    x: 0,
    y: 1,
    w: 1,
    h: 7,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "AttainmentGoal",
    x: 0,
    y: 2,
    w: 1,
    h: 7,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "AverageHandleTimeGoal",
    x: 0,
    y: 4,
    w: 1,
    h: 7,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "QualityGoal",
    x: 0,
    y: 6,
    w: 1,
    h: 7,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "AdherenceGoal",
    x: 0,
    y: 7,
    w: 1,
    h: 7,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
];
