export const chart_layout = [
  {
    i: "ScoreCardTable",
    x: 0,
    y: 0,
    w: 2,
    h: 10,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },

  {
    i: "AttainmentGoal",
    x: 1,
    y: 2,
    w: 2,
    h: 10,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "AverageHandleTimeGoal",
    x: 1,
    y: 4,
    w: 2,
    h: 10,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "QualityGoal",
    x: 1,
    y: 6,
    w: 2,
    h: 10,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "AdherenceGoal",
    x: 1,
    y: 8,
    w: 2,
    h: 10,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "AverageScore",
    x: 1,
    y: 8,
    w: 2,
    h: 10,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "TeamOne",
    x: 1,
    y: 0,
    w: 2,
    h: 10,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },

  {
    i: "TeamTwo",
    x: 0,
    y: 2,
    w: 2,
    h: 10,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "TeamThree",
    x: 1,
    y: 4,
    w: 2,
    h: 10,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "TeamFour",
    x: 1,
    y: 6,
    w: 2,
    h: 10,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "TeamFive",
    x: 1,
    y: 8,
    w: 2,
    h: 10,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
  {
    i: "TeamSix",
    x: 1,
    y: 8,
    w: 2,
    h: 10,
    resizeHandles: ["se", "sw", "ne", "nw"],
  },
];
